### ISSUE TITLE
Leaving Sleep HQ. How do I reset the script to work with Oscar?

### ISSUE THREAD

**Issue by jonalan2003** [iitggithub/ezshare_cpap#1]
Sol,

I will be leaving Sleep HQ when my subscription expires in November. How do I reset the script to not upload to Sleep HQ. I plan on continuing with Oscar. Thanks for your help. I truly appreciate all the work you have done on this project.

Jon Campbell

**Comment by iitggithub** [comment]
Run the script with the parameter --remove-sleephq

For example, if you run your script normally using

`./sync.sh`

Execute it (only once) like so:

`./sync.sh --remove-sleephq`

This will remove the credentials and device ID from your keychain.

The next time you run the script, it will ask you if you want to configure sleep hq uploads. Simply answer no to the question and it won't prompt you again until you run another --remove-sleephq.
