### ISSUE TITLE
Script Stopped Working

### ISSUE THREAD

**Issue by jonalan2003** [iitggithub/ezshare_cpap#2]
Sol. 3 days ago the script stopped working. It runs but as it executes it keeps saying permission denied. When it ends it says all data already up to date, but it is not downloading anything. In the Datalog folder the new days folder is there but it is empty.

I copied all of the existing data to my hard drive. Reformatted the SD Card put the data back and tried again. Same result.

I then read your instructions about the hidden files. I just deleted the whole SD_Card folder and tried starting over with a full sync.I get a DATALOG folder that has the folders for the days but they are empty. There is a SETTINGS folder but it is empty There are no other files.

If I read the SD card with my computer all the files are there. I can usecOscar or Sleep HQ to read my data. 

How do I fix this? I really miss using the script. It is so easy and fast.

Thank you, Jon Campbell

**Comment by jonalan2003** [comment]
Sol. I got it working again. I copied the data from my SD card to my computer. Reformatted the SD card and started over. This morning it worked just fine.

**Comment by iitggithub** [comment]
Ok i'll close this one out for now. If it happens again, please let me know. Hasn't been any changes to the script since September.
